import "./globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

/* 
  Interestingly, customers who use Next.js cannot have an async static loader,
  because the framework will inject this tag before sync ones for some reason.  
 */

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* eslint-disable-next-line */}
        <script src="https://web.cmp.usercentrics-sandbox.eu/ui/modules/autoblocker.js"></script>
        {/* eslint-disable-next-line */}
        <script
          src="https://web.cmp.usercentrics-sandbox.eu/ui/loader.js"
          data-settings-id="H8UPjXU8uQQ7GP"
          id="usercentrics-cmp"
        ></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
